volumes: 
  v_emakas_shop_db:
  v_emakas_shop_app:
services: 
  emakas_shop_app:
    build: "."
    volumes:
      - v_emakas_shop_app:/App/wwwroot/
    ports:
      - 5047:8080
    restart: always
  emakas_shop_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - v_emakas_shop_db:/var/lib/postgresql/data
    restart: always


  db_test:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - v_emakas_shop_db:/var/lib/postgresql/data
    restart: always
