<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>10</LangVersion>
    <RootNamespace>shop-app.contract</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="FluentValidation" Version="11.2.1" />
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\shop_app.business\shop_app.business.csproj" />
    <ProjectReference Include="..\shop_app.data\shop_app.data.csproj" />
    <ProjectReference Include="..\shop_app.entity\shop_app.entity.csproj" />
  </ItemGroup>

</Project>
