<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>shop_app.service</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>10</LangVersion>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\shop_app.data\shop_app.data.csproj" />
		<ProjectReference Include="..\shop_app.shared\shop_app.shared.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Minio" Version="7.0.0" />
	</ItemGroup>


</Project>
